### ISSUE TITLE
FPS Drop

### ISSUE THREAD

**Issue by sutnax** [Toufool/AutoSplit#192] opened 2022-12-31 19:05 UTC
Hello it is FPS dropping and i tried to limit fps but it didn't work it still doing that pls fix that shit

**Comment by Toufool** [comment] 2022-12-31 19:52
A lesson for when you are writing issues on github if you want someone to help you:

1. Don't be rude
2. Give more information (screenshots, settings files, clips of the fps drops (is the fps of the game dropping or of the app?), size of the region you are capturing, game that you are capturing, reproduction steps, literally anything)

I can not look into your issue until you provide more of this info, because it sounds like it may be an issue with how your autosplit is set up, but I can't tell because you gave no useful information

**Comment by Avasam** [comment] 2022-12-31 20:03
@Toufool Remind me to setup Github issue templates at some point.

**Comment by Avasam** [comment] 2023-04-22 03:10
Closed by #211

**Closed by Avasam** 2023-04-22 03:10 UTC
Labels: question, optimization, Fix pending, 2.0.0 Request
